/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectbasdat;

import com.toedter.calendar.JCalendar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    PreparedStatement pst = null;
    ResultSet rs;
    Statement st;
    Connection con;
    final DefaultTableModel dtmTransaksi;
    final DefaultTableModel dtmPelanggan;
    final DefaultTableModel dtmLensa;
    final DefaultTableModel dtmFrame;
    final DefaultTableModel dtmDetail;
    public MenuUtama() {
        initComponents();
        dtmTransaksi = new DefaultTableModel();
        dtmPelanggan = new DefaultTableModel();
        dtmLensa = new DefaultTableModel();
        dtmFrame = new DefaultTableModel();
        dtmDetail = new DefaultTableModel();
        
        tabelTransaksi.setModel(dtmTransaksi);  
        dtmTransaksi.addColumn("Nomor Transaksi");
        dtmTransaksi.addColumn("Tanggal Transaksi");
        dtmTransaksi.addColumn("Nama Pelanggan");
        dtmTransaksi.addColumn("Total Harga");
        
        tabelPelanggan.setModel(dtmPelanggan);
        dtmPelanggan.addColumn("Nama Pelanggan");
        dtmPelanggan.addColumn("Nomor Telepon");
        
        tabelLensa.setModel(dtmLensa);
        dtmLensa.addColumn("ID Barang");
        dtmLensa.addColumn("Nama Lensa");
        dtmLensa.addColumn("Power");
        dtmLensa.addColumn("Silinder");
        dtmLensa.addColumn("Stok");
        dtmLensa.addColumn("Harga Satuan");
        
        tabelFrame.setModel(dtmFrame);
        dtmFrame.addColumn("ID Barang");
        dtmFrame.addColumn("Merek Frame");
        dtmFrame.addColumn("Harga");
        
        tabelDetail.setModel(dtmDetail);
        dtmDetail.addColumn("Nomor Transaksi");
        dtmDetail.addColumn("ID Lensa");
        dtmDetail.addColumn("ID Frame");
        dtmDetail.addColumn("Banyaknya");
        dtmDetail.addColumn("Jumlah Harga");
        
        update_table();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Method untuk update Tabel
    private void update_table(){
        dtmTransaksi.getDataVector().removeAllElements();
        dtmTransaksi.fireTableDataChanged();
        
        dtmPelanggan.getDataVector().removeAllElements();
        dtmPelanggan.fireTableDataChanged();
        
        dtmFrame.getDataVector().removeAllElements();
        dtmFrame.fireTableDataChanged();
        
        dtmLensa.getDataVector().removeAllElements();
        dtmLensa.fireTableDataChanged();
        
        dtmDetail.getDataVector().removeAllElements();
        dtmDetail.fireTableDataChanged();
        
        try{
            con = BasisData.getKoneksi();
            try(Statement s = con.createStatement()){
                String sqlTransaksi = "SELECT * FROM transaksi";
                String sqlPelanggan = "SELECT * FROM pelanggan";
                String sqlFrame = "SELECT * FROM data_frame";
                String sqlLensa = "SELECT * FROM data_lensa";
                String sqlDetail = "SELECT * FROM pesanan_detail";
                rs = s.executeQuery(sqlTransaksi);
                while(rs.next()){
                    Object[] x = new Object[4];
                    x[0] = rs.getString("no_transaksi");
                    x[1] = rs.getString("tanggal_transaksi");
                    x[2] = rs.getString("nama");
                    x[3] = rs.getString("total_harga");
                    dtmTransaksi.addRow(x);
                }
                rs.close();
            }
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Update Table Transaksi");
        }
        
        try{
            con = BasisData.getKoneksi();
            try(Statement s = con.createStatement()){
                String sqlTransaksi = "SELECT * FROM transaksi";
                String sqlPelanggan = "SELECT * FROM pelanggan";
                String sqlFrame = "SELECT * FROM data_frame";
                String sqlLensa = "SELECT * FROM data_lensa";
                String sqlDetail = "SELECT * FROM pesanan_detail";
                rs = s.executeQuery(sqlPelanggan);
                while(rs.next()){
                    Object[] x = new Object[2];
                    x[0] = rs.getString("nama");
                    x[1] = rs.getString("no_telpon");
                    dtmPelanggan.addRow(x);
                }
                rs.close();
            }
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Update Table Pelanggan");
        }
        
        try{
            con = BasisData.getKoneksi();
            try(Statement s = con.createStatement()){
                String sqlTransaksi = "SELECT * FROM transaksi";
                String sqlPelanggan = "SELECT * FROM pelanggan";
                String sqlFrame = "SELECT * FROM data_frame";
                String sqlLensa = "SELECT * FROM data_lensa";
                String sqlDetail = "SELECT * FROM pesanan_detail";
                rs = s.executeQuery(sqlFrame);
                while(rs.next()){
                    Object[] x = new Object[4];
                    x[0] = rs.getString("id_barang");
                    x[1] = rs.getString("mere_frame");
                    x[2] = rs.getString("harga_frame");
                    x[3] = rs.getString("stok");
                    dtmFrame.addRow(x);
                }
                rs.close();
            }
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Update Table Frame");
        }
        
        try{
            con = BasisData.getKoneksi();
            try(Statement s = con.createStatement()){
                String sqlTransaksi = "SELECT * FROM transaksi";
                String sqlPelanggan = "SELECT * FROM pelanggan";
                String sqlFrame = "SELECT * FROM data_frame";
                String sqlLensa = "SELECT * FROM data_lensa";
                String sqlDetail = "SELECT * FROM pesanan_detail";
                rs = s.executeQuery(sqlLensa);
                while(rs.next()){
                    Object[] x = new Object[6];
                    x[0] = rs.getString("id_barang");
                    x[1] = rs.getString("nama_lensa");
                    x[2] = rs.getString("power");
                    x[3] = rs.getString("silinder");
                    x[4] = rs.getString("stok");
                    x[5] = rs.getString("harga_satuan");
                    dtmLensa.addRow(x);
                }
                rs.close();
            }
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Update Table Lensa");
        }
        
        try{
            con = BasisData.getKoneksi();
            try(Statement s = con.createStatement()){
                String sqlTransaksi = "SELECT * FROM transaksi";
                String sqlPelanggan = "SELECT * FROM pelanggan";
                String sqlFrame = "SELECT * FROM data_frame";
                String sqlLensa = "SELECT * FROM data_lensa";
                String sqlDetail = "SELECT * FROM pesanan_detail";
                rs = s.executeQuery(sqlDetail);
                while(rs.next()){
                    Object[] x = new Object[5];
                    x[0] = rs.getString("no_transaksi");
                    x[1] = rs.getString("id_lensa");
                    x[2] = rs.getString("id_frame");
                    x[3] = rs.getString("banyaknya");
                    x[4] = rs.getString("jumlah_harga");
                    dtmDetail.addRow(x);
                }
                rs.close();
            }
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Update Table Detail");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        tfCariTransaksi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tfCariPelanggan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNamaLensa = new javax.swing.JTextField();
        tfSilinderLensa = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelLensa = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        btnTbhLensa = new javax.swing.JButton();
        btnUbhLensa = new javax.swing.JButton();
        btnHpsLensa = new javax.swing.JButton();
        tfCariLensa = new javax.swing.JTextField();
        tfPowerLensa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfStokLensa = new javax.swing.JTextField();
        tfHargaSatuan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfIdLensa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfCariDetail = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelDetail = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfNoTransaksi = new javax.swing.JTextField();
        tfNamaPlg = new javax.swing.JTextField();
        tfTglTransaksi = new com.toedter.calendar.JDateChooser();
        jPanel12 = new javax.swing.JPanel();
        btnTbhTransaksi = new javax.swing.JButton();
        btnUbhTransaksi = new javax.swing.JButton();
        btnHpsTransaksi = new javax.swing.JButton();
        tfNoTelp = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfIdBrg = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfBanyaknya = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfIdFrame = new javax.swing.JTextField();
        tfMerekFrame = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelFrame = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnTbhFrame = new javax.swing.JButton();
        btnUbahFrame = new javax.swing.JButton();
        btnHpsFrame = new javax.swing.JButton();
        tfCariFrame = new javax.swing.JTextField();
        tfHargaFrame = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfStokFrame = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPTIK MURAH");

        JTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMOR TRANSAKSI", "TANGGAL TRANSAKSI", "NAMA PELANGGAN", "TOTAL HARGA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        tfCariTransaksi.setText("Masukkan Nomer Transaksi");
        tfCariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tfCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        JTabbedPane1.addTab("Transaksi", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfCariPelanggan.setText("Masukkan nama pelanggan");
        tfCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariPelangganActionPerformed(evt);
            }
        });

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAMA PELANGGAN", "NOMOR TELEPON"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCariPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tfCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        JTabbedPane1.addTab("Pelanggan", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("NAMA LENSA");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("POWER");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("SILINDER");

        tfNamaLensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaLensaActionPerformed(evt);
            }
        });

        tabelLensa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID BARANG", "NAMA LENSA", "POWER", "SILINDER", "STOK", "HARGA SATUAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelLensa);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTbhLensa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTbhLensa.setText("TAMBAH");
        btnTbhLensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhLensaActionPerformed(evt);
            }
        });

        btnUbhLensa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUbhLensa.setText("UBAH");

        btnHpsLensa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHpsLensa.setText("HAPUS");
        btnHpsLensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsLensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnTbhLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnUbhLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnHpsLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTbhLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfCariLensa.setText("Masukkan ID lensa");
        tfCariLensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariLensaActionPerformed(evt);
            }
        });

        tfPowerLensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPowerLensaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("STOK");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("HARGA SATUAN");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("ID LENSA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfCariLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfSilinderLensa, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfPowerLensa, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfNamaLensa)
                                        .addComponent(tfStokLensa)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfHargaSatuan))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(tfIdLensa))))))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tfCariLensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfIdLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNamaLensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPowerLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSilinderLensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfStokLensa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTabbedPane1.addTab("Lensa", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfCariDetail.setText("Masukkan No.Transaksi");
        tfCariDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariDetailActionPerformed(evt);
            }
        });

        tabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO.TRANSAKSI", "ID LENSA", "ID FRAME", "BANYAKNYA", "JUMLAH HARGA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelDetail);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCariDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tfCariDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        JTabbedPane1.addTab("Detail Transakasi", jPanel5);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("NOMOR TRANSAKSI");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("TANGGAL TRANSAKSI");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("NAMA PELANGGAN");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("NO.TELEPON");

        tfNoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTransaksiActionPerformed(evt);
            }
        });

        tfTglTransaksi.setDateFormatString("yyyy-MM-dd");

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTbhTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTbhTransaksi.setText("TAMBAH");
        btnTbhTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhTransaksiActionPerformed(evt);
            }
        });

        btnUbhTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUbhTransaksi.setText("UBAH");

        btnHpsTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHpsTransaksi.setText("HAPUS");
        btnHpsTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnTbhTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnUbhTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnHpsTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTbhTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("ID BARANG");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("BANYAKNYA");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(tfBanyaknya)
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfIdBrg)
                                    .addComponent(tfNamaPlg)
                                    .addComponent(tfNoTransaksi)
                                    .addComponent(tfTglTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                                    .addComponent(tfNoTelp))))
                        .addGap(14, 14, 14))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(tfTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNamaPlg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tfNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfIdBrg, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfBanyaknya, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTabbedPane1.addTab("Input Transaksi", jPanel11);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("ID");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("MEREK");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("HARGA");

        tfIdFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdFrameActionPerformed(evt);
            }
        });

        tabelFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "MEREK", "HARGA", "STOK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelFrame);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTbhFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTbhFrame.setText("TAMBAH");
        btnTbhFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhFrameActionPerformed(evt);
            }
        });

        btnUbahFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUbahFrame.setText("UBAH");
        btnUbahFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahFrameActionPerformed(evt);
            }
        });

        btnHpsFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHpsFrame.setText("HAPUS");
        btnHpsFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnTbhFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnUbahFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnHpsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTbhFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tfCariFrame.setText("Masukkan ID Barang");
        tfCariFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariFrameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("STOK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfCariFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(120, 120, 120))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(116, 116, 116)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfMerekFrame)
                                        .addComponent(tfHargaFrame)
                                        .addComponent(tfStokFrame)
                                        .addComponent(tfIdFrame)))))))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tfCariFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfIdFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMerekFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfStokFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfHargaFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTabbedPane1.addTab("Frame", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(JTabbedPane1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariTransaksiActionPerformed

    private void tfCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariPelangganActionPerformed

    private void tfIdFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdFrameActionPerformed

    private void btnTbhFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhFrameActionPerformed
        // TODO add your handling code here:
        String idBarang = tfIdFrame.getText();
        String merkFrame = tfMerekFrame.getText();
        String stok = tfStokFrame.getText();
        String hargaFrame = tfHargaFrame.getText();
        int stokInt = Integer.parseInt(stok);
        int hargaSatuanInt = Integer.parseInt(hargaFrame);

        if (idBarang.isEmpty() || merkFrame.isEmpty() || stok.isEmpty() || hargaFrame.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }    
        con = BasisData.getKoneksi();
        String sqlLensa = "INSERT INTO data_frame (id_barang, mere_frame, harga_frame, stok) VALUES (?, ?, ?, ?)";
        try{
            // Operasi pertama
            pst = con.prepareStatement(sqlLensa);
            pst.setString(1, idBarang);
            pst.setString(2, merkFrame);
            pst.setInt(3, hargaSatuanInt);
            pst.setInt(4, stokInt);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan pada tabel Frame", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("Error pada frame bang");
        }
//        clear();
        update_table();
    }//GEN-LAST:event_btnTbhFrameActionPerformed

    private void tfCariFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariFrameActionPerformed

    private void btnUbahFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahFrameActionPerformed

    private void tfNamaLensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaLensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaLensaActionPerformed

    private void btnTbhLensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhLensaActionPerformed
        // TODO add your handling code here:
        String idBarang = tfIdLensa.getText();
        String namaLensa = tfNamaLensa.getText();
        String power = tfPowerLensa.getText();
        String silinder = tfSilinderLensa.getText();
        String stok = tfStokLensa.getText();
        String hargaSatuan = tfHargaSatuan.getText();
        double powerDesimal = Double.parseDouble(power);
        double silinderDesimal = Double.parseDouble(silinder);
        int stokInt = Integer.parseInt(stok);
        int hargaSatuanInt = Integer.parseInt(hargaSatuan);

        if (idBarang.isEmpty() || namaLensa.isEmpty() || power.isEmpty() || silinder.isEmpty() || stok.isEmpty() || hargaSatuan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }    
        con = BasisData.getKoneksi();
        String sqlLensa = "INSERT INTO data_lensa (id_barang, nama_lensa, power, silinder, stok, harga_satuan) VALUES (?, ?, ?, ?, ?, ?)";
        try{
            // Operasi pertama
            pst = con.prepareStatement(sqlLensa);
            pst.setString(1, idBarang);
            pst.setString(2, namaLensa);
            pst.setDouble(3, powerDesimal);
            pst.setDouble(4, silinderDesimal);
            pst.setInt(5, stokInt);
            pst.setInt(6, hargaSatuanInt);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan pada tabel detail", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("Error pada lensa bang");
        }
//        clear();
        update_table();
    }//GEN-LAST:event_btnTbhLensaActionPerformed

    private void btnHpsLensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsLensaActionPerformed
        // TODO add your handling code here:
        String id_lensa = tfIdLensa.getText();

        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan ID Lensa  : "+id_lensa+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = BasisData.getKoneksi();
            try{
                String sql = "DELETE FROM data_lensa WHERE id_barang=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, id_lensa);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        //update_table();
    }//GEN-LAST:event_btnHpsLensaActionPerformed

    private void tfCariLensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariLensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariLensaActionPerformed

    private void tfPowerLensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPowerLensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPowerLensaActionPerformed

    private void tfCariDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariDetailActionPerformed

    private void tfNoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTransaksiActionPerformed

    private void btnTbhTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhTransaksiActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String noTransaksi = tfNoTransaksi.getText();
        String tgl = date.format(tfTglTransaksi.getDate());
        String nama = tfNamaPlg.getText();
        String telp = tfNoTelp.getText();
        String idBarang = tfIdBrg.getText();
        String banyaknya = tfBanyaknya.getText();
        int banyak = Integer.parseInt(banyaknya);

        if (nama.isEmpty() || telp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }    
        con = BasisData.getKoneksi();
        String sqlTransaksi = "INSERT INTO transaksi (no_transaksi, tanggal_transaksi, nama, total_harga) VALUES (?, ?, ?, ?)";
        String sqlPelanggan = "INSERT INTO pelanggan (nama, no_telpon) VALUES (?, ?)";
        String sqlDetailTransaksi = null;
        if(idBarang.charAt(0) == 'F'){
            sqlDetailTransaksi = "INSERT INTO pesanan_detail (no_transaksi, id_frame, banyaknya, jumlah_harga) VALUES (?, ?, ?, ?)";
        }
        else if(idBarang.charAt(0) == 'L'){
            sqlDetailTransaksi = "INSERT INTO pesanan_detail (no_transaksi, id_lensa, banyaknya, jumlah_harga) VALUES (?, ?, ?, ?)";
        }
        try{
            // Operasi pertama   
            String sqlSelectHarga = null;
            int hargaSatuan = 0;
            if(idBarang.charAt(0) == 'F'){
                sqlSelectHarga = "SELECT harga_frame FROM data_frame WHERE id_barang = ?";
                pst = con.prepareStatement(sqlSelectHarga);
                pst.setString(1, idBarang);
                ResultSet rs = pst.executeQuery();

                // Mendapatkan harga_satuan dari hasil query SELECT              
                if (rs.next()) {
                    hargaSatuan = rs.getInt("harga_frame");
                }
            }
            else if(idBarang.charAt(0) == 'L'){
                sqlSelectHarga = "SELECT harga_satuan FROM data_lensa WHERE id_barang = ?";  
                pst = con.prepareStatement(sqlSelectHarga);
                pst.setString(1, idBarang);
                ResultSet rs = pst.executeQuery();

                // Mendapatkan harga_satuan dari hasil query SELECT                
                if (rs.next()) {
                    hargaSatuan = rs.getInt("harga_satuan");
                }
            }
            pst = con.prepareStatement(sqlTransaksi);
            pst.setString(1, noTransaksi);
            pst.setString(2, tgl);
            pst.setString(3, nama);
            pst.setInt(4, banyak * hargaSatuan);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan pada tabel transaksi", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);

            // Operasi kedua
            pst = con.prepareStatement(sqlPelanggan);
            pst.setString(1, nama);
            pst.setString(2, telp);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan pada tabel pelanggan", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);

            // Operasi ketiga                       
            pst = con.prepareStatement(sqlDetailTransaksi);
            pst.setString(1, noTransaksi);
            pst.setString(2, idBarang);
            pst.setInt(3, banyak);
            pst.setInt(4, banyak * hargaSatuan);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan pada tabel detail", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("Error pada detail bang");
        }
//        clear();
        update_table();
    }//GEN-LAST:event_btnTbhTransaksiActionPerformed

    private void btnHpsTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsTransaksiActionPerformed
        // TODO add your handling code here:
        String no_transaksi = tfNoTransaksi.getText();

        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan No Transaksi  : "+no_transaksi+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = BasisData.getKoneksi();   
            try{
                String sql = "DELETE FROM transaksi WHERE no_transaksi=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, no_transaksi);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        update_table();
    }//GEN-LAST:event_btnHpsTransaksiActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnHpsFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsFrameActionPerformed
        // TODO add your handling code here:
        String id_frame = tfIdFrame.getText();

        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan ID Frame  : "+id_frame+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = BasisData.getKoneksi();
            try{
                String sql = "DELETE FROM data_frame WHERE id_barang=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, id_frame);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        //update_table();
    }//GEN-LAST:event_btnHpsFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane1;
    private javax.swing.JButton btnHpsFrame;
    private javax.swing.JButton btnHpsLensa;
    private javax.swing.JButton btnHpsTransaksi;
    private javax.swing.JButton btnTbhFrame;
    private javax.swing.JButton btnTbhLensa;
    private javax.swing.JButton btnTbhTransaksi;
    private javax.swing.JButton btnUbahFrame;
    private javax.swing.JButton btnUbhLensa;
    private javax.swing.JButton btnUbhTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelDetail;
    private javax.swing.JTable tabelFrame;
    private javax.swing.JTable tabelLensa;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField tfBanyaknya;
    private javax.swing.JTextField tfCariDetail;
    private javax.swing.JTextField tfCariFrame;
    private javax.swing.JTextField tfCariLensa;
    private javax.swing.JTextField tfCariPelanggan;
    private javax.swing.JTextField tfCariTransaksi;
    private javax.swing.JTextField tfHargaFrame;
    private javax.swing.JTextField tfHargaSatuan;
    private javax.swing.JTextField tfIdBrg;
    private javax.swing.JTextField tfIdFrame;
    private javax.swing.JTextField tfIdLensa;
    private javax.swing.JTextField tfMerekFrame;
    private javax.swing.JTextField tfNamaLensa;
    private javax.swing.JTextField tfNamaPlg;
    private javax.swing.JTextField tfNoTelp;
    private javax.swing.JTextField tfNoTransaksi;
    private javax.swing.JTextField tfPowerLensa;
    private javax.swing.JTextField tfSilinderLensa;
    private javax.swing.JTextField tfStokFrame;
    private javax.swing.JTextField tfStokLensa;
    private com.toedter.calendar.JDateChooser tfTglTransaksi;
    // End of variables declaration//GEN-END:variables
}
